version: 2

models:
  - name: ecommerce
    description: "A starter ecom model"
    schema: "test"
    columns:
      - name: role_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
